<?php

$plugin_cf['news']['csv_filepath']="content/plugins/news";
$plugin_cf['news']['csv_delimiter']="#";
$plugin_cf['news']['csv_enclosure']="\"";
$plugin_cf['news']['categories_sort_function']="news_categories_sort_asc";
$plugin_cf['news']['blog']="true";
$plugin_cf['news']['date_format']="y/m/d";
$plugin_cf['news']['date_format_backend']="y/m/d";
$plugin_cf['news']['template_newsticker']="false";
$plugin_cf['news']['template_newsslider']="false";
$plugin_cf['news']['template_newsscroller']="true";
$plugin_cf['news']['rss_file']="rss.php";
$plugin_cf['news']['pagination_backend']="10";
$plugin_cf['news']['pagination_archive']="10";
$plugin_cf['news']['newsticker_speed']="0.1";
$plugin_cf['news']['newsticker_controls']="false";
$plugin_cf['news']['newsticker_title_text']="Latest";
$plugin_cf['news']['newsticker_effect']="reveal";
$plugin_cf['news']['newsticker_delay']="2000";
$plugin_cf['news']['newsticker_fade_in_speed']="600";
$plugin_cf['news']['newsticker_fade_out_speed']="300";
$plugin_cf['news']['newsslider_speed']="2000";
$plugin_cf['news']['newsslider_pause_hover']="true";
$plugin_cf['news']['newsscroller_speed']="0.07";
$plugin_cf['news']['datepicker_format']="yy/mm/dd";
$plugin_cf['news']['jquery_core']="jquery-1.9.1.min.js";
$plugin_cf['news']['jquery_ui']="jquery-ui-1.8.21.custom.min.js";
$plugin_cf['news']['jquery_ui_css']="jquery-ui-1.8.21.custom.css";

?>
